apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend  # Deployment name changed to backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chai-backend
  template:
    metadata:
      labels:
        app: chai-backend
    spec:
      containers:
      - name: backend  # Container name changed to backend
        image: BACKEND_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000