name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-e88d1c23-e44c-4d58-8dd
  REGION: us-east1
  REPOSITORY: ankit-repo
  IMAGE_NAME: nginx-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/198436119624/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: git-hub-access-sa@project-e88d1c23-e44c-4d58-8dd.iam.gserviceaccount.com

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}
          
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ankit-cluster
          location: us-east1-b

      - name: Replace Image Tag
        run: |
          sed -i "s|:latest|:${{ github.sha }}|g" deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml