name: CI-CD to GKE

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-e88d1c23-e44c-4d58-8dd
  REGION: us-east1
  GAR_REPOSITORY: ankit-repo
  IMAGE_NAME: nginx-demo
  CLUSTER_NAME: ankit-cluster
  CLUSTER_LOCATION: us-east1-b

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/198436119624/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: git-hub-access-sa@project-e88d1c23-e44c-4d58-8dd.iam.gserviceaccount.com

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            -t us-east1-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push \
            us-east1-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/nginx-demo \
          nginx-demo=us-east1-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/nginx-demo --timeout=180s

      - name: Verify Deployment
        run: |
          kubectl get deployment nginx-demo
          kubectl get pods
          kubectl get svc